const fs = require("fs");
const path = require("path");
const { getPaths } = require("./config");
const { scanRepo } = require("./scan");
const { extractFile, buildSymbols } = require("./extract");
const { staleness } = require("./query");

const marker = "<!-- agent-index:compact -->";

function approxTokens(text) {
  return text.split(/\s+/).filter(Boolean).length;
}

function readOriginalAgents(paths) {
  const current = fs.existsSync(paths.agentsPath) ? fs.readFileSync(paths.agentsPath, "utf8") : "";
  if (current.includes(marker) && fs.existsSync(paths.fullAgentsPath)) return fs.readFileSync(paths.fullAgentsPath, "utf8");
  return current;
}

function contextSummary(files) {
  const buckets = {};
  for (const file of files) {
    const top = file.path.includes("/") ? file.path.split("/")[0] : "root";
    if (!buckets[top]) buckets[top] = { files: 0, signals: 0 };
    buckets[top].files += 1;
    buckets[top].signals += file.signals.length;
  }
  return Object.entries(buckets)
    .sort((a, b) => b[1].signals - a[1].signals)
    .slice(0, 10)
    .map(([name, data]) => ({ name, ...data }));
}

function renderCompactAgents({ originalAgents, files, symbols, packageFile, mcpFile, contexts, rootName }) {
  const wantedScripts = ["build", "check", "benchmark", "summary", "test"];
  const scriptSignals = packageFile ? packageFile.signals.filter((signal) => signal.kind === "script") : [];
  const scripts = wantedScripts
    .filter((name) => scriptSignals.some((signal) => signal.symbol === `script:${name}`))
    .map((name) => `\`npm run ${name}\``);
  const mcps = (mcpFile ? mcpFile.signals.filter((signal) => signal.kind === "mcp-server").slice(0, 6) : [])
    .map((signal) => `\`${signal.symbol.replace("mcp:", "")}\``);
  const contextLines = contexts.slice(0, 8).map((context) => `\`${context.name}\`(${context.files}/${context.signals})`);

  return `${marker}
# ${rootName}

Compact AGENTS generated by agent-index. Full original: \`.agent-index/AGENTS.full.md\`. Generated index: \`.agent-index/index.json\`.

Rules: keep broad context in the index, keep local prompts tight, and query the index before large reads or multi-file edits.

Project: indexed workspace with high-signal summaries for source files, scripts, MCP config, and symbols.

Commands: ${scripts.join(", ") || "inspect package.json"}.

MCP: ${mcps.join(", ") || "no MCP servers indexed"}. Start the local MCP bridge with \`agent-index mcp\`.

Context map: ${contextLines.join(", ") || "no files indexed yet"}. Format is files/signals.

Always retrieve compressed context first: \`agent-index summary\`; search: \`agent-index search <topic>\`; file: \`agent-index file <path>\`; symbol: \`agent-index symbol <name>\`.

Generated: ${files.length} files, ${Object.keys(symbols).length} symbols, original ${approxTokens(originalAgents)} approx tokens.
`;
}

function build(rootInput) {
  const paths = getPaths(rootInput);
  fs.mkdirSync(paths.indexDir, { recursive: true });

  const originalAgents = readOriginalAgents(paths);
  fs.writeFileSync(paths.fullAgentsPath, originalAgents, "utf8");

  const scanned = scanRepo(paths.root);
  const files = scanned.files.map(extractFile);
  const symbols = buildSymbols(files);
  const packageFile = files.find((file) => file.path === "package.json");
  const mcpFile = files.find((file) => file.path === ".mcp.json");
  const contexts = contextSummary(files);
  const compact = renderCompactAgents({
    originalAgents,
    files,
    symbols,
    packageFile,
    mcpFile,
    contexts,
    rootName: path.basename(paths.root)
  });

  fs.writeFileSync(paths.agentsPath, compact, "utf8");

  const compression = {
    originalTokens: approxTokens(originalAgents),
    compactTokens: approxTokens(compact),
    ratio: originalAgents ? Number((1 - approxTokens(compact) / approxTokens(originalAgents)).toFixed(4)) : 0
  };

  const generatedAt = new Date().toISOString();
  const index = { generatedAt, compression, contexts, skipped: scanned.skipped.length };
  const staleFiles = Object.fromEntries(scanned.files.map((file) => [file.path, { hash: file.hash, size: file.size, mtimeMs: file.mtimeMs }]));

  fs.writeFileSync(paths.indexPath, JSON.stringify(index, null, 2), "utf8");
  fs.writeFileSync(paths.filesPath, JSON.stringify(files, null, 2), "utf8");
  fs.writeFileSync(paths.symbolsPath, JSON.stringify(symbols, null, 2), "utf8");
  fs.writeFileSync(paths.stalenessPath, JSON.stringify({ generatedAt, files: staleFiles }, null, 2), "utf8");

  return {
    root: paths.root,
    files: files.length,
    symbols: Object.keys(symbols).length,
    skipped: scanned.skipped.length,
    compression
  };
}

function check(rootInput) {
  const result = staleness(rootInput);
  if (result.staleCount > 0) {
    const error = new Error(`Agent index is stale: ${result.staleCount} files changed.`);
    error.details = result;
    throw error;
  }
  return { ok: true, ...result };
}

function benchmark(rootInput) {
  const paths = getPaths(rootInput);
  const original = fs.existsSync(paths.fullAgentsPath) ? fs.readFileSync(paths.fullAgentsPath, "utf8") : "";
  const compact = fs.existsSync(paths.agentsPath) ? fs.readFileSync(paths.agentsPath, "utf8") : "";
  const originalTokens = approxTokens(original);
  const compactTokens = approxTokens(compact);
  const ratio = originalTokens ? 1 - compactTokens / originalTokens : 0;
  return { originalTokens, compactTokens, compressionRatio: Number(ratio.toFixed(4)) };
}

module.exports = { approxTokens, build, check, benchmark };
